### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by Hackeruncle** [ApacheInfra/superset#3046]
**click sclice in the web, these error:** 

```
      Traceback (most recent call last):
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/views.py", line 453, in list
    widgets=widgets)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 13, in block "content"
    {% block list_list scoped %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 15, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/base_list.html", line 23, in top-level template code
    {% block begin_loop_values %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 45, in block "begin_loop_values"
    {% for item in value_columns %}
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/runtime.py", line 410, in __init__
    self._after = self._safe_next()
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/jinja2/runtime.py", line 430, in _safe_next
    return next(self._iterator)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/models/base.py", line 87, in get_values
    retdict[col] = self._get_attr_value(item, col)
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/flask_appbuilder/models/base.py", line 36, in _get_attr_value
    if not hasattr(item, col):
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/superset/models/core.py", line 212, in slice_link
    url = self.slice_url
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/superset/models/core.py", line 198, in slice_url
    obj=self, params=parse.quote(json.dumps(self.form_data))))
  File "/user/apps/hduser1301/superset-test/jy-super/lib/python3.5/site-packages/superset/models/core.py", line 182, in form_data
    form_data = json.loads(self.params)
  File "/usr/local/python3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    **raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**
```

**Comment by xrmx** [comment]
Please add all the missing information from the bug report template.

**Comment by Hackeruncle** [comment]
ENV: python3.5 and superset 0.17.5
1.The superset is running long, today i create a sclice in web,
i don't know what happened?  Then i click  sclices tab in the web, this error:"500 - Internal Server Error"

2.I analyze these error detail,
"File "/usr/local/python3/lib/python3.5/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/python3/lib/python3.5/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

3.I suspect that  it's related to the Python version.

**4.I install an new superset with python2.7.5,configure metadata with config.py.**

**5.Install this command with "pip install Flask-WTF==0.14"**

**6.Start the new superset,open the web,click sclices tab, 
and i find that there one sclice with name is null in the web. I delete this sclice.**

7.Refresh the original superset web, it's ok.

**Comment by Hackeruncle** [comment]
I closed it.
