### ISSUE TITLE
[Bug] Couldn't parse date string

### ISSUE THREAD

**Issue by wei-hai** [ApacheInfra/superset#3051]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

I just installed superset on Ubuntu and tried it, and the dashboard could not display date string.
<img width="1256" alt="screen shot 2017-06-27 at 9 25 12 pm" src="https://user-images.githubusercontent.com/2936715/27620570-485349b6-5b7f-11e7-8515-5de0262e92d0.png">

```
2017-06-28 12:16:29,194:ERROR:root:'module' object has no attribute 'URBNFRuleSetTag'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/superset/utils.py", line 205, in parse_human_datetime
    cal = parsedatetime.Calendar()
  File "/usr/local/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 270, in __init__
    self.ptc = Constants()
  File "/usr/local/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 2374, in __init__
    self.locale = get_icu(self.localeID)
  File "/usr/local/lib/python2.7/dist-packages/parsedatetime/pdt_locales/icu.py", line 54, in get_icu
    rbnf = pyicu.RuleBasedNumberFormat(pyicu.URBNFRuleSetTag.SPELLOUT, icu)
AttributeError: 'module' object has no attribute 'URBNFRuleSetTag'
2017-06-28 12:16:29,195:ERROR:root:Couldn't parse date string [7 days ago]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 238, in get_payload
    df = self.get_df()
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 66, in get_df
    query_obj = self.query_obj()
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 1402, in query_obj
    d = super(HeatmapViz, self).query_obj()
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 139, in query_obj
    from_dttm = utils.parse_human_datetime(since)
  File "/usr/local/lib/python2.7/dist-packages/superset/utils.py", line 209, in parse_human_datetime
    raise ValueError("Couldn't parse date string [{}]".format(s))
ValueError: Couldn't parse date string [7 days ago]
```

**Comment by wei-hai** [comment]
upgrading pyicu to latest version shall fix it
