### ISSUE TITLE
[sqllab] auto preview on table name with Chinese(unicode?) failed

### ISSUE THREAD

**Issue by STILLSHI** [ApacheInfra/superset#3063]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"version": "0.18.5", "GIT_SHA": ""}
python3.5
mysql: 5.7.18-0ubuntu0.16.04.1

### Expected results

the result of the auto table preview should be:
中文字段1,中文字段2,中文字段3
1,1,zh中文
2,2,zh中文中文

### Actual results

Returned an HTML page sourcecode, here is the stacktrace I copied from the textbox of the html page. however, if you then select the data from the query everything works fine.

Traceback (most recent call last): File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__ return self.wsgi_app(environ, start_response) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app response = self.handle_exception(e) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception reraise(exc_type, exc_value, tb) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise raise value File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app response = self.full_dispatch_request() File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request rv = self.handle_user_exception(e) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception reraise(exc_type, exc_value, tb) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise raise value File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request rv = self.dispatch_request() File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps return f(self, *args, **kwargs) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/models/core.py", line 759, in wrapper value = f(*args, **kwargs) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/views/core.py", line 1977, in sql_json rejected_tables = self.rejected_datasources(sql, mydb, schema) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/views/base.py", line 127, in rejected_datasources superset_query = sql_parse.SupersetQuery(sql) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 21, in __init__ self.__extract_from_token(statement) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 128, in __extract_from_token self.__process_identifier(item) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 67, in __process_identifier self._table_names.add(SupersetQuery.__get_full_name(identifier)) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 49, in __get_full_name identifier.tokens[2].value) IndexError: list index out of range

### Steps to reproduce

#table structure
create table ZYDB2.中文表名
(
中文字段1 int null,
中文字段2 int null,
中文字段3 varchar(80) null
)
;
##value:
中文字段1,中文字段2,中文字段3
1,1,zh中文
2,2,zh中文中文

add datasource in superset:
mysql://still2:XXXXXXXXXX@ipaddr/ZYDB2?charset=utf8

then goto sql lab
select the table: 中文表名
sqllab will automatically render a preview of the table
it will fail by returning a lot of html code.

thanks

**Comment by STILLSHI** [comment]
<img width="1030" alt="screen shot 2017-06-30 at 5 06 02 pm" src="https://user-images.githubusercontent.com/3668587/27728953-7b9a237e-5db6-11e7-9c61-a43a375b5c58.png">
<img width="1042" alt="screen shot 2017-06-30 at 5 06 15 pm" src="https://user-images.githubusercontent.com/3668587/27728957-7d880412-5db6-11e7-968e-25d0cfb6856f.png">

**Comment by xrmx** [comment]
Please copy the stacktrace from the logs so it's formatted properly, also please use triple backticks for quoting it.

**Comment by STILLSHI** [comment]
hello xrmx, could you advise where I can find the logs? Really I can't find it. Googled it should be a file named superset.log but I can't find it...

regards

**Comment by STILLSHI** [comment]
[logs.html.zip](https://github.com/ApacheInfra/superset/files/1114674/logs.html.zip)

here is the html page i saved from the text returned.

**Comment by xrmx** [comment]
It depends on how are you running superset. If from console you have them there, if running from systemd you have them in journald, etc...

**Comment by STILLSHI** [comment]
thank you. I manually adjusted the log so it could be easier to read.

Traceback (most recent call last): File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1997, in call return self.wsgi_app(environ, start_response) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1985, in wsgi_app response = self.handle_exception(e) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1540, in handle_exception reraise(exc_type, exc_value, tb) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/_compat.py", 
line 33, in reraise raise value File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1982, in wsgi_app response = self.full_dispatch_request() File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1614, in full_dispatch_request rv = self.handle_user_exception(e) 
File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1517, in handle_user_exception reraise(exc_type, exc_value, tb) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/_compat.py", 
line 33, in reraise raise value File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1612, in full_dispatch_request rv = self.dispatch_request() File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", 
line 1598, in dispatch_request return self.view_functionsrule.endpoint File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", 
line 52, in wraps return f(self, *args, **kwargs) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/models/core.py", 
line 759, in wrapper value = f(*args, **kwargs) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/views/core.py", 
line 1977, in sql_json rejected_tables = self.rejected_datasources(sql, mydb, schema) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/views/base.py", 
line 127, in rejected_datasources superset_query = sql_parse.SupersetQuery(sql) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", 
line 21, in init self.__extract_from_token(statement) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", 
line 128, in __extract_from_token self.__process_identifier(item) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", 
line 67, in __process_identifier self._table_names.add(SupersetQuery.__get_full_name(identifier)) File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 49, in __get_full_name identifier.tokens[2].value) IndexError: list index out of range

**Comment by STILLSHI** [comment]
got it from the console:

2017-06-30 17:30:15,429:INFO:root:Parsing with sqlparse statement SELECT `中文字段1`,
       `中文字段2`,
       `中文字段3`
FROM ZYDB2.中文表名
LIMIT 100
2017-06-30 17:30:15,443:INFO:werkzeug:210.13.83.19 - - [30/Jun/2017 17:30:15] "POST /superset/sql_json/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/models/core.py", line 759, in wrapper
    value = f(*args, **kwargs)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/views/core.py", line 1977, in sql_json
    rejected_tables = self.rejected_datasources(sql, mydb, schema)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/views/base.py", line 127, in rejected_datasources
    superset_query = sql_parse.SupersetQuery(sql)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 21, in __init__
    self.__extract_from_token(statement)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 128, in __extract_from_token
    self.__process_identifier(item)
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 67, in __process_identifier
    self._table_names.add(SupersetQuery.__get_full_name(identifier))
  File "/root/ZYDATA/zypy3/lib/python3.5/site-packages/superset/sql_parse.py", line 49, in __get_full_name
    identifier.tokens[2].value)
IndexError: list index out of range
